# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

display_url: https://kidsprotectteam.org.au # This url will display in the top-right of the CMS
media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit


  - name: "pages"
    label: "Page"
    editor:
      preview: false
    folder: content/pages
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: Title, name: title, widget: string}
      - label: 'Template'
        name: 'template'
        widget: 'select'
        options: ["Page", "Form"]
        default: 'Page'
      - {label: URL Slug, name: slug, widget: string}
      - {label: Content, name: body, widget: markdown, required: false}
      - {label: Audio, name: audio, widget: file, required: false}
      - {label: Happy message, name: happyMessage, widget: text, required: false}
      - {label: Neutral message, name: neutralMessage, widget: text, required: false}
      - {label: Sad message, name: sadMessage, widget: text, required: false}
      - {label: Form Title, name: formTitle, widget: string, required: false}


  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "content/settings/global.yml"
        label: "Global Settings"
        name: "global-settings"
        fields:
          - {label: Site Title, name: siteTitle, widget: string}
          - {label: Site Url, name: siteUrl, widget: string, required: false}
          - {label: Site Description, name: siteDescription, widget: text, required: false}
          - {label: Blue Title, name: blueTitle, widget: string, required: false}
          - {label: Blue message, name: blueMessage, widget: text, required: false}
          - {label: Blue link URL, name: blueLinkURL, widget: string, required: false}
          - {label: Office Address, name: officeAddress, widget: text, required: false}
          - {label: Phone, name: phone, widget: string, required: false}
          - {label: Email, name: email, widget: string, required: false}
          - label: Social Media
            name: socialMediaCard
            widget: object
            fields:
              - {label: Twitter URL, name: twitterURL, widget: string, required: false}
              - {label: Facebook URL, name: facebookURL, widget: string, required: false}
              - {label: Linkedin URL, name: linkedinURL, widget: string, required: false}
              - {label: Instagram URL, name: instagramURL, widget: string, required: false}
          - {label: Header Meta / Scripts, name: headerScripts, widget: text, required: false}
          - {label: Enable Service Worker Pre-Cache, name: enableServiceWorker, widget: boolean, required: false}
